theme: "hugo-PaperMod"
baseURL: https://enn7.netlify.app
languageCode: en-us
title: ENN7 Conference
params:
    defaultTheme: light
    ShowBreadCrumbs: true

menu:
  main:
    - identifier: cfp
      name: Call for Papers
      url: /cfp/
    - identifier: program
      name: Program
      url: /program/
    - identifier: registration
      name: Registration
      url: /registration/
